### ISSUE TITLE
Can you please make this snapping option disabled by default?

### ISSUE THREAD

**Issue by GIS-PuppetMaster** [AlphaGaming7780/ExtraDetailingTools#24]
![image](https://github.com/AlphaGaming7780/ExtraDetailingTools/assets/31107435/5d319eb1-be0e-4f42-9c17-8feca3eb6230)
This snapping option is really inconvenience when building roads in areas with trees. My road keep climb to the trees and create a slop automatically

**Comment by AlphaGaming7780** [comment]
This was disabled by default before the update, after the update is not possible anymore to make it disabled by default.
